### ISSUE TITLE
Question : Does it support font awesome animations

### ISSUE THREAD

**Issue by ricky11** [iconify/iconify#171]
Font awesome supports tags like `pulse` `spin` which are wrappers around active css classes?  Would iconify support the same?

Thanks
Rishi

**Comment by cyberalien** [comment]
Those are simple css animations. You can add them to your code by copying css:
```css
.fa-spin {
  -webkit-animation: fa-spin 2s infinite linear;
          animation: fa-spin 2s infinite linear; }

.fa-pulse {
  -webkit-animation: fa-spin 1s infinite steps(8);
          animation: fa-spin 1s infinite steps(8); }

@-webkit-keyframes fa-spin {
  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg); }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg); } }

@keyframes fa-spin {
  0% {
    -webkit-transform: rotate(0deg);
            transform: rotate(0deg); }
  100% {
    -webkit-transform: rotate(360deg);
            transform: rotate(360deg); } }

```
