### ISSUE TITLE
[Idea] An "animate" attribute

### ISSUE THREAD

**Issue by jordymeow** [iconify/iconify#21]
Hi,

I love Iconify, so thanks a lot for your work. This is awesome.

A feature I would really like to see is an _animate_ attribute. We could set it to _rotate_, _pulsing_, _jumping_, etc. That would be useful to use it as a spinner, interesting effects on hover, or to get user's attention.

Cheers :)

**Comment by cyberalien** [comment]
Thank you!

Animations are done by adding some css, so you can already do that: add animation to stylesheet, add class to icon placeholder. Something like this:

```css
.spin-icon {
	animation: spin 2s linear infinite;
}

@keyframes spin {
	from {
		transform: rotate(0deg);
	}
	to {
		transform: rotate(360deg);
	}
}

```

```html
<span class="iconify spin-icon" data-icon="uil:spin"></span>
```
