### ISSUE TITLE
Why not set min-width to avoid layout shift

### ISSUE THREAD

**Issue by lovetingyuan** [iconify/iconify#252]
When I use web-component `iconify-icon`, it render icon with some defer because api request.
I will add the style to preallocate space to avoid layout shifts.

```css
iconify-icon {
  min-width: 1em;
  min-height: 1em;
}
```
