### ISSUE TITLE
@iconify/tailwindcss redundant code

### ISSUE THREAD

**Issue by sillvva** [iconify/iconify#290]
When I hover over the class `icon-[mdi--magnify]`, I see the following:

```css
.icon-\[mdi--magnify\] {
  display: inline-block;
  width: 1em;
  height: 1em;
  background-color: currentColor;
  -webkit-mask-image: var(--svg);
  mask-image: var(--svg);
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
  -webkit-mask-size: 100% 100%;
  mask-size: 100% 100%;
  --svg: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='black' d='M9.5 3A6.5 6.5 0 0 1 16 9.5c0 1.61-.59 3.09-1.56 4.23l.27.27h.79l5 5l-1.5 1.5l-5-5v-.79l-.27-.27A6.516 6.516 0 0 1 9.5 16A6.5 6.5 0 0 1 3 9.5A6.5 6.5 0 0 1 9.5 3m0 2C7 5 5 7 5 9.5S7 14 9.5 14S14 12 14 9.5S12 5 9.5 5'/%3E%3C/svg%3E");
}
```

Everything but the variable is redundant from icon to icon, and should probably be in a separate class to avoid repeated code in the final bundle. If you had 50 different icons on a page, it would have 50 instances of those CSS properties.

Instead of doing `icon-[mdi--magnify]`, what about `icon mdi-[magnify]`?

```css
/* component class */
.icon {
  display: inline-block;
  width: 1em;
  height: 1em;
  background-color: currentColor;
  -webkit-mask-image: var(--svg);
  mask-image: var(--svg);
  -webkit-mask-repeat: no-repeat;
  mask-repeat: no-repeat;
  -webkit-mask-size: 100% 100%;
  mask-size: 100% 100%;
}

/* utility class */
.mdi-\[magnify\]
  --svg: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24' width='24' height='24'%3E%3Cpath fill='black' d='M9.5 3A6.5 6.5 0 0 1 16 9.5c0 1.61-.59 3.09-1.56 4.23l.27.27h.79l5 5l-1.5 1.5l-5-5v-.79l-.27-.27A6.516 6.516 0 0 1 9.5 16A6.5 6.5 0 0 1 3 9.5A6.5 6.5 0 0 1 9.5 3m0 2C7 5 5 7 5 9.5S7 14 9.5 14S14 12 14 9.5S12 5 9.5 5'/%3E%3C/svg%3E");
}
```

For now, I'm doing this manually in my tailwind config file
```js
import { icons as mdi } from "@iconify-json/mdi";

plugin(function ({ addComponents, addUtilities, theme }) {
	addComponents({
		".iconify": {
			display: "inline-block",
			width: theme("width.4"),
			height: theme("height.4"),
			backgroundColor: theme("colors.current"),
			maskImage: "var(--svg)",
			maskRepeat: "no-repeat",
			maskSize: "100% 100%"
		}
	});

	const mdiIcons = Object.entries(mdi.icons);
	for (const [name, icon] of mdiIcons) {
		const path = encodeURIComponent(icon.body.replace(` fill="currentColor"`, "")).replace(/%20/g, " ").replace(/%22/g, "'");
		addUtilities({
			[`.mdi-${name}`]: {
				"--svg": `url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 24 24'%3E${path}%3C/svg%3E")`
			}
		});
	}
})
```
