### ISSUE TITLE
@iconify/tailwind can't use underline

### ISSUE THREAD

**Issue by cyrilf** [iconify/iconify#293]
If I'm using any icon, let say this one: `<span class="icon-[ph--github-logo] underline"/>` then the `underline` won't work.

The issue also occurs if I do it on a wrapping element:
```html
<a class="underline">
  <span class="icon-[ph--github-logo]" />
  github.com
</a>
```

This is the generated CSS:
```css
.icon-\[ph--github-logo\] {
    display: inline-block;
    width: 1em;
    height: 1em;
    background-color: currentColor;
    mask-image: var(--svg);
    mask-repeat: no-repeat;
    mask-size: 100% 100%;
    --svg: url(data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 256 256' width='256' height='256'%3E%3Cpath fill='black' d='M208.31 [...]}
```

The `mask-image` is the culprit here. It seems to be fully hiding anything.
Is there any way to display an underline below the icon element?

Thanks!
