### ISSUE TITLE
[@iconify/tailwind] icons from comments are bundled

### ISSUE THREAD

**Issue by mergehez** [iconify/iconify#358]
if you have an icon in a comment that is not used anywhere else, the plugin generates CSS for it. This unnecessarily increases the bundle size. 

to reproduce:

1. create a comment with an icon that is not used anywhere else
```html
<!--<i class="icon icon-[twemoji--left-right-arrow]"></i>-->
```
2. build the project (you don't get any warnings here)
3. search for the icon name in the dist folder. In my case it is "twemoji--left-right-arrow". the 'unnecessary' css is indeed generated
```css
.icon-\[twemoji--left-right-arrow\] {
  background-image: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 36 36' width='36' height='36'%3E%3Cpath fill='%233B88C3' d='M36 32a4 4 0 0 1-4 4H4a4 4 0 0 1-4-4V4a4 4 0 0 1 4-4h28a4 4 0 0 1 4 4z'/%3E%3Cpath fill='%23FFF' d='M13 9L3 18l10 9zm20 9L23 9v18z'/%3E%3Cpath fill='%23FFF' d='M12 14h12v8H12z'/%3E%3C/svg%3E");
}
```

I know this is a tailwind css bug but they probably won't to solve the bug: https://github.com/tailwindlabs/tailwindcss/issues/11524
