### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by hose1021** [iconify/iconify#54]
Hello, problem is in `transform: rotate(360deg);`
I using tailwind.css and if I use `animate-spin` class to `span` icon, style `transform` for svg, does not allow adding animation.

P.S.
```css
.animate-spin{
animation: spin 1s linear infinite;
}

@keyframes spin {
from {
transform: rotate(0deg);
}   to {
transform: rotate(360deg);
} 
```

**Comment by cyberalien** [comment]
Works fine for me: https://codepen.io/cyberalien/pen/yLagZPN

**Comment by hose1021** [comment]
No, it's not works, I think it maybe fails because style coming after class on convertering,maybe is it?

I added in pen tailwind.css and one more example. Please check

https://codepen.io/hose1021/pen/mdrRojy

**Comment by cyberalien** [comment]
It is caused by bug in Tailwind. This is their spin animation code:
```css
@keyframes spin {
  to {
    transform: rotate(360deg);
  }
}
```
There is no "from", so it transforms from initial state. SVG rendered by Iconify have style set to `transform: rotate(360deg)` to fix SVG rendering bug in Firefox. Because initial state matches final state, no animation happens.

You can test that by using this:
```html
<p class="animate-spin w-7" style="transform: rotate(0deg);">example 1</p>
<p class="animate-spin w-7" style="transform: rotate(360deg);">example 2</p>
```
First example will spin, second example will not, even though their style has identical layout.

Workaround is to set transformation on icon:
```html
<span class="iconify animate-spin" data-icon="uil:spin" style="transform: none;"></span>
```
